
version: '3.2'
services:
    mysql_db:
        container_name: mysql_db
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
            - '3301:3306'
        restart: always
    spring_db:
        build: .
        ports:
            - '8085:8085'
        depends_on:
            mysql_db:
                condition: service_healthy
            
            